### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FERDIZ-afk** [Hisoka-Morrou/hisoka-waweb.js#1]
![Screenshot_2022-04-19-21-24-50-30](https://user-images.githubusercontent.com/69185890/164026625-0c7a2bda-59ed-41d6-b8b5-1d697feafed1.png)

##What's error

**Comment by DikaArdnt** [comment]
> ![Screenshot_2022-04-19-21-24-50-30](https://user-images.githubusercontent.com/69185890/164026625-0c7a2bda-59ed-41d6-b8b5-1d697feafed1.png)
> 
> ##What's error

Error di { name: "Dika Ardnt." }
